/*
 * fw_image.h — public interface extract.
 *
 * The CAN Triple firmware is closed source. This file is generated from the
 * firmware's own header by stripping every comment, so the declarations below
 * are byte-identical to the ones the shipped binary was built against. It
 * exists for one reason: to let this repository's application compile and link
 * against firmware/lib/libct_device_core.a.
 *
 * The reasoning, the wire protocol, the flash layout and the engine's design
 * are deliberately not here. For the host side of the protocol, read the
 * application's own gui/src/protocol/.
 *
 * Generated by gui/publish/make_public_headers.py — do not edit.
 */

#ifndef FW_IMAGE_H
#define FW_IMAGE_H

#include <stdint.h>

#ifdef __cplusplus
#  define FW_STATIC_ASSERT(cond, msg) static_assert(cond, msg)
extern "C" {
#else
#  define FW_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
#endif

#define FW_FLASH_BASE        0x08000000u
#define FW_FLASH_END         0x08080000u
#define FW_BANK2_BASE        0x08040000u
#define FW_PAGE_SIZE              0x800u

#define FW_BOOTLOADER_BASE   0x08000000u
#define FW_BOOTLOADER_SIZE       0x4000u

#define FW_APP_BASE          0x08004000u
#define FW_APP_MAX_SIZE         0x1E000u

#define FW_STAGING_BASE      0x08061000u
#define FW_STAGING_SIZE         0x1E000u

#define FW_BCB_BASE          0x0807F000u
#define FW_BCB_SIZE              0x1000u

FW_STATIC_ASSERT(FW_BOOTLOADER_BASE + FW_BOOTLOADER_SIZE == FW_APP_BASE,
                 "bootloader must end exactly where the app slot begins");
FW_STATIC_ASSERT(FW_APP_BASE + FW_APP_MAX_SIZE <= FW_BANK2_BASE,
                 "app slot must stay inside bank 1 or read-while-write is lost");
FW_STATIC_ASSERT(FW_STAGING_SIZE == FW_APP_MAX_SIZE,
                 "staging must be able to hold any image the app slot can");
FW_STATIC_ASSERT(FW_STAGING_BASE >= FW_BANK2_BASE,
                 "staging must be in bank 2 so downloads do not stall the core");
FW_STATIC_ASSERT(FW_STAGING_BASE + FW_STAGING_SIZE == FW_BCB_BASE,
                 "boot control block must sit immediately above staging");
FW_STATIC_ASSERT(FW_BCB_BASE + FW_BCB_SIZE == FW_FLASH_END,
                 "boot control block must end at the top of flash");
FW_STATIC_ASSERT(FW_BOOTLOADER_SIZE % FW_PAGE_SIZE == 0 &&
                 FW_APP_MAX_SIZE % FW_PAGE_SIZE == 0 &&
                 FW_STAGING_SIZE % FW_PAGE_SIZE == 0 &&
                 FW_BCB_SIZE % FW_PAGE_SIZE == 0,
                 "every region must be a whole number of erase pages");
FW_STATIC_ASSERT(FW_BCB_SIZE / FW_PAGE_SIZE == 2,
                 "the boot control block ping-pongs between exactly two pages");

#if defined(__arm__)
#  define FW_FLASH_PTR(addr) ((const void *)(uintptr_t)(addr))
#else

const void *fw_flash_ptr(uint32_t addr);
#  define FW_FLASH_PTR(addr) fw_flash_ptr(addr)
#endif

#define FW_IMAGE_HEADER_OFFSET   0x200u

#define FW_IMAGE_MAGIC       0x57465443u
#define FW_IMAGE_HDR_VERSION        1u

#define FW_PRODUCT_CAN_TRIPLE  0x4333u

#define FW_IMAGE_ALIGN              8u

typedef struct {
    uint32_t magic;
    uint16_t header_version;
    uint16_t product_id;

    uint32_t image_size;

    uint32_t image_crc32;

    uint16_t fw_version_major;
    uint16_t fw_version_minor;
    uint16_t fw_version_patch;

    uint16_t flash_store_version;

    uint32_t min_bootloader_version;

    uint32_t build_id;
    char     build_desc[32];
} FwImageHeader;

FW_STATIC_ASSERT(sizeof(FwImageHeader) == 64, "FwImageHeader must be 64 bytes");
FW_STATIC_ASSERT(FW_IMAGE_HEADER_OFFSET + sizeof(FwImageHeader) < 0x400u,
                 "header must not run past the space reserved for it");

#define FW_IMAGE_CRC_OFFSET \
    (FW_IMAGE_HEADER_OFFSET + (uint32_t)__builtin_offsetof(FwImageHeader, image_crc32))

#define FW_IMAGE_MIN_SIZE (FW_IMAGE_HEADER_OFFSET + (uint32_t)sizeof(FwImageHeader))

#define FW_BCB_MAGIC         0x42435443u
#define FW_BCB_RECORD_SIZE          32u
#define FW_BCB_SLOTS_PER_PAGE  (FW_PAGE_SIZE / FW_BCB_RECORD_SIZE)

#define FW_MAX_COMMIT_ATTEMPTS      3u

enum {
    FW_STATE_IDLE    = 0,
    FW_STATE_PENDING = 1,
};

enum {
    FW_RESULT_NONE            = 0,
    FW_RESULT_OK              = 1,
    FW_RESULT_BAD_MAGIC       = 2,
    FW_RESULT_WRONG_PRODUCT   = 3,
    FW_RESULT_BAD_SIZE        = 4,
    FW_RESULT_BAD_CRC         = 5,
    FW_RESULT_BL_TOO_OLD      = 6,
    FW_RESULT_ERASE_FAILED    = 7,
    FW_RESULT_PROGRAM_FAILED  = 8,
    FW_RESULT_VERIFY_FAILED   = 9,
    FW_RESULT_GAVE_UP         = 10,
};

typedef struct {
    uint32_t magic;
    uint32_t seq;
    uint8_t  state;
    uint8_t  attempts;
    uint8_t  last_result;
    uint8_t  reserved0;
    uint32_t staged_size;
    uint32_t staged_crc32;
    uint32_t reserved1;
    uint32_t reserved2;
    uint32_t crc32;
} BootControlRecord;

FW_STATIC_ASSERT(sizeof(BootControlRecord) == FW_BCB_RECORD_SIZE,
                 "BootControlRecord must be exactly one slot");
FW_STATIC_ASSERT(FW_BCB_RECORD_SIZE % FW_IMAGE_ALIGN == 0,
                 "a record must be a whole number of programmable doublewords");

uint32_t fw_crc32(const void *data, uint32_t len);

#define FW_CRC32_INIT 0xFFFFFFFFu
uint32_t fw_crc32_update(uint32_t crc, const void *data, uint32_t len);
static inline uint32_t fw_crc32_final(uint32_t crc) { return crc ^ 0xFFFFFFFFu; }

uint8_t fw_image_validate(const void *base, uint32_t avail, uint32_t bl_version);

static inline const FwImageHeader *fw_image_header(const void *base, uint32_t avail)
{
    if (avail < FW_IMAGE_MIN_SIZE) {
        return (const FwImageHeader *)0;
    }
    return (const FwImageHeader *)((const uint8_t *)base + FW_IMAGE_HEADER_OFFSET);
}

#define FW_BOOTLOADER_VERSION 2u

#define FW_BL_INFO_OFFSET 0x200u
#define FW_BL_INFO_MAGIC  0x4C425443u

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t app_base;
    uint32_t reserved;
} BootloaderInfo;

FW_STATIC_ASSERT(sizeof(BootloaderInfo) == 16, "BootloaderInfo must be 16 bytes");

#if defined(__arm__)
static inline uint32_t fw_bootloader_version(void)
{
    const BootloaderInfo *info =
        (const BootloaderInfo *)(FW_BOOTLOADER_BASE + FW_BL_INFO_OFFSET);
    return (info->magic == FW_BL_INFO_MAGIC) ? info->version : 0u;
}
#else

static inline uint32_t fw_bootloader_version(void)
{
    return FW_BOOTLOADER_VERSION;
}
#endif

#ifdef __cplusplus
}
#endif

#endif
