/*
 * protocol.h — public interface extract.
 *
 * The CAN Triple firmware is closed source. This file is generated from the
 * firmware's own header by stripping every comment, so the declarations below
 * are byte-identical to the ones the shipped binary was built against. It
 * exists for one reason: to let this repository's application compile and link
 * against firmware/lib/libct_device_core.a.
 *
 * The reasoning, the wire protocol, the flash layout and the engine's design
 * are deliberately not here. For the host side of the protocol, read the
 * application's own gui/src/protocol/.
 *
 * Generated by gui/publish/make_public_headers.py — do not edit.
 *
 * Reduced to the single declaration script_exec.h needs — ScriptStatus, the
 * CMD_SCRIPT_STATUS reply shape. The command table, the record layouts and the
 * store contract are not published.
 *
 * The pack(1) is not decoration: this struct crosses the boundary to the
 * prebuilt device-core library, which was compiled with it. Extracting the
 * fields without it yields a naturally-aligned struct of a different size.
 */

#ifndef CT_PROTOCOL_H
#define CT_PROTOCOL_H

#include <stdint.h>

#define MAX_SIGNALS              1000

#pragma pack(push, 1)
typedef struct {
    uint8_t  present;
    uint8_t  verify_result;
    uint8_t  fault;
    uint8_t  suspended;
    uint32_t code_bytes;
    uint32_t last_cost;
    uint32_t peak_cost;
    uint16_t num_state;
    uint16_t budget;
    uint32_t last_cycles;
    uint32_t peak_cycles;
    uint8_t  cycles_valid;
} ScriptStatus;
#pragma pack(pop)

#endif
