/*
 * script_exec.h — public interface extract.
 *
 * The CAN Triple firmware is closed source. This file is generated from the
 * firmware's own header by stripping every comment, so the declarations below
 * are byte-identical to the ones the shipped binary was built against. It
 * exists for one reason: to let this repository's application compile and link
 * against firmware/lib/libct_device_core.a.
 *
 * The reasoning, the wire protocol, the flash layout and the engine's design
 * are deliberately not here. For the host side of the protocol, read the
 * application's own gui/src/protocol/.
 *
 * Generated by gui/publish/make_public_headers.py — do not edit.
 */

#ifndef SCRIPT_EXEC_H
#define SCRIPT_EXEC_H

#include <stdbool.h>
#include <stdint.h>

#include "protocol.h"
#include "script_vm.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float (*read_signal)(uint16_t idx);
    void  (*write_signal)(uint16_t idx, float value);
} ScriptHost;

void script_exec_init(const ScriptHost *host);

uint8_t script_exec_load(const void *image, uint32_t avail, uint16_t max_signals);

void script_exec_clear(void);

void script_exec_begin_tick(void);

uint8_t script_exec_on_tick(void);

void script_exec_status(ScriptStatus *out);

bool script_exec_running(void);

float script_exec_state(uint16_t idx);

#ifdef __cplusplus
}
#endif

#endif
