/*
 * script_vm.h — public interface extract.
 *
 * The CAN Triple firmware is closed source. This file is generated from the
 * firmware's own header by stripping every comment, so the declarations below
 * are byte-identical to the ones the shipped binary was built against. It
 * exists for one reason: to let this repository's application compile and link
 * against firmware/lib/libct_device_core.a.
 *
 * The reasoning, the wire protocol, the flash layout and the engine's design
 * are deliberately not here. For the host side of the protocol, read the
 * application's own gui/src/protocol/.
 *
 * Generated by gui/publish/make_public_headers.py — do not edit.
 */

#ifndef SCRIPT_VM_H
#define SCRIPT_VM_H

#include <stdint.h>

#ifdef __cplusplus
#  define SCRIPT_STATIC_ASSERT(c, m) static_assert(c, m)
extern "C" {
#else
#  define SCRIPT_STATIC_ASSERT(c, m) _Static_assert(c, m)
#endif

#define SCRIPT_MAGIC              0x43535443u

#define SCRIPT_BYTECODE_VERSION       1u
#define SCRIPT_MIN_SUPPORTED_VERSION  1u

#define SCRIPT_NUM_REGS           64u
#define SCRIPT_NUM_STATE          64u

#define SCRIPT_INSTR_SIZE         8u

#define SCRIPT_TICK_BUDGET        2000u

#define SCRIPT_COST_HEAVY         8u

#define SCRIPT_COST_DIVIDE        4u

#define SCRIPT_CYCLE_CEILING      170000u

#define SCRIPT_CYCLE_CHECK        8u

#define SCRIPT_MAX_CODE_BYTES     8192u
#define SCRIPT_MAX_INSTRUCTIONS   (SCRIPT_MAX_CODE_BYTES / SCRIPT_INSTR_SIZE)

#define SCRIPT_OP_ARITH_MAX       0x1Eu

enum {
    SCRIPT_OP_LOADK    = 0x20,
    SCRIPT_OP_LOADSIG  = 0x21,
    SCRIPT_OP_STORESIG = 0x22,
    SCRIPT_OP_LOADST   = 0x23,
    SCRIPT_OP_STOREST  = 0x24,
    SCRIPT_OP_MOV      = 0x25,
    SCRIPT_OP_JMP      = 0x26,
    SCRIPT_OP_JZ       = 0x27,
    SCRIPT_OP_JNZ      = 0x28,
    SCRIPT_OP_HALT     = 0x2F,

};

typedef struct {
    uint8_t  op;
    uint8_t  dst;
    uint8_t  a;
    uint8_t  b;
    uint32_t imm;
} ScriptInstr;

SCRIPT_STATIC_ASSERT(sizeof(ScriptInstr) == SCRIPT_INSTR_SIZE,
                     "ScriptInstr must be exactly 8 bytes with no padding");

#define SCRIPT_NO_ENTRY  0xFFFFFFFFu

typedef struct {
    uint32_t magic;
    uint16_t version;
    uint16_t num_state;
    uint32_t code_bytes;
    uint32_t code_crc32;
    uint32_t entry_tick;
    uint32_t entry_rx;
    uint32_t entry_tx;
    uint32_t reserved;
} ScriptHeader;

SCRIPT_STATIC_ASSERT(sizeof(ScriptHeader) == 32, "ScriptHeader must be 32 bytes");

#define SCRIPT_MIN_IMAGE_BYTES (sizeof(ScriptHeader) + SCRIPT_INSTR_SIZE)

enum {
    SCRIPT_OK               = 0,
    SCRIPT_ERR_MAGIC        = 1,
    SCRIPT_ERR_VERSION      = 2,
    SCRIPT_ERR_SIZE         = 3,
    SCRIPT_ERR_CRC          = 4,
    SCRIPT_ERR_STATE_COUNT  = 5,
    SCRIPT_ERR_OPCODE       = 6,
    SCRIPT_ERR_REGISTER     = 7,
    SCRIPT_ERR_SIGNAL       = 8,
    SCRIPT_ERR_STATE_INDEX  = 9,
    SCRIPT_ERR_JUMP         = 10,
    SCRIPT_ERR_ENTRY        = 11,
    SCRIPT_ERR_NO_HALT      = 12,

    SCRIPT_ERR_VERSION_OLD  = 13,
    SCRIPT_ERR_NONFINITE    = 14,
    SCRIPT_ERR_RESERVED     = 15,
};

enum {
    SCRIPT_FAULT_NONE    = 0,
    SCRIPT_FAULT_BUDGET  = 1,

    SCRIPT_FAULT_OVERRUN = 2,
};

uint32_t script_crc32(const void *data, uint32_t len);

uint32_t script_op_cost(uint8_t op);

uint8_t script_verify(const void *base, uint32_t avail, uint16_t max_signals);

static inline const ScriptHeader *script_header(const void *base, uint32_t avail)
{
    if (avail < sizeof(ScriptHeader)) {
        return (const ScriptHeader *)0;
    }
    return (const ScriptHeader *)base;
}

static inline const ScriptInstr *script_code(const void *base)
{
    return (const ScriptInstr *)((const uint8_t *)base + sizeof(ScriptHeader));
}

#ifdef __cplusplus
}
#endif

#endif
