/*
 * seal.h — public interface extract.
 *
 * The CAN Triple firmware is closed source. This file is generated from the
 * firmware's own header by stripping every comment, so the declarations below
 * are byte-identical to the ones the shipped binary was built against. It
 * exists for one reason: to let this repository's application compile and link
 * against firmware/lib/libct_device_core.a.
 *
 * The reasoning, the wire protocol, the flash layout and the engine's design
 * are deliberately not here. For the host side of the protocol, read the
 * application's own gui/src/protocol/.
 *
 * Generated by gui/publish/make_public_headers.py — do not edit.
 */

#ifndef SEAL_H
#define SEAL_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SEAL_SALT_LEN   16u
#define SEAL_TAG_LEN    16u
#define SEAL_INDEX_LEN  4u
#define SEAL_OVERHEAD   (SEAL_INDEX_LEN + SEAL_TAG_LEN)
#define SEAL_KEY_LEN    32u

typedef struct {
    uint8_t enc[SEAL_KEY_LEN];
    uint8_t mac[SEAL_KEY_LEN];
} SealKeys;

void seal_derive(const uint8_t *fleet_key, uint32_t fleet_key_len,
                 const uint8_t salt[SEAL_SALT_LEN], SealKeys *out);

uint32_t seal_frame(const SealKeys *keys, uint32_t index, const uint8_t *plain,
                    uint32_t plain_len, uint8_t *out);

bool seal_open(const SealKeys *keys, uint32_t expected_index, const uint8_t *in,
               uint32_t in_len, uint8_t *out, uint32_t *out_len);

void seal_wipe(SealKeys *keys);

#ifdef __cplusplus
}
#endif

#endif
