#include "asc_log.h"

#include <QDateTime>
#include <QLocale>

namespace ct {

namespace {

// CAN FD DLC nibble for a byte count (0-8 map 1:1; 12->9, 16->10, ... 64->15).
int len2dlc(int len)
{
    if (len <= 8)
        return len;
    static const int kFd[] = {12, 16, 20, 24, 32, 48, 64};
    for (int i = 0; i < 7; ++i)
        if (len <= kFd[i])
            return 9 + i;
    return 15;
}

} // namespace

QString ascHeader(const QDateTime &when)
{
    const QLocale c = QLocale::c(); // stable, English names, no regional formatting
    QString h;
    h += QStringLiteral("date ") + c.toString(when, QStringLiteral("yyyyMMdd HH:mm:ss"))
         + QLatin1Char('\n');
    h += QStringLiteral("base hex  timestamps absolute\n");
    h += QStringLiteral("Begin Triggerblock ")
         + c.toString(when, QStringLiteral("ddd MMM dd hh:mm:ss AP yyyy")) + QLatin1Char('\n');
    h += QStringLiteral("     0.000000 Start of measurement\n");
    h += QStringLiteral("// Generated by CAN Triple Device Manager\n");
    h += QStringLiteral("// Timestamp  Bus     CANId Rx/Tx d Length Data\n");
    return h;
}

QString ascFrameLine(const MonitorStreamPayload &f, quint32 t0)
{
    // Relative to the first buffered frame. Guard against a backwards jump
    // (device reboot mid-capture) so it can't underflow into an absurd value.
    const double ts = f.timestamp_ms >= t0 ? double(f.timestamp_ms - t0) / 1000.0 : 0.0;
    const bool ext = f.flags & MONFLAG_EXTENDED;
    const bool brs = f.flags & MONFLAG_BRS;
    const bool esi = f.flags & MONFLAG_ESI;
    const bool fd = (f.flags & MONFLAG_FD) || brs; // BRS is only set on FD frames

    // Standard ids as %03X, extended as %08X; extended also gets the Vector 'x'
    // suffix (appended after upper-casing so the marker stays lowercase).
    QString idStr =
        QStringLiteral("%1").arg(f.can_id, ext ? 8 : 3, 16, QLatin1Char('0')).toUpper();
    if (ext)
        idStr += QLatin1Char('x');

    const int len = qMin<int>(f.data_len, 64);
    QString dataStr;
    dataStr.reserve(len * 3);
    for (int i = 0; i < len; ++i) {
        if (i)
            dataStr += QLatin1Char(' ');
        dataStr += QStringLiteral("%1").arg(f.data[i], 2, 16, QLatin1Char('0')).toUpper();
    }
    const QString dir = f.direction ? QStringLiteral("Tx") : QStringLiteral("Rx");

    if (fd) {
        // Vector CAN FD line: CANFD channel dir id name BRS ESI DLC dataLength
        // data messageDuration messageLength flags CRC + 4 bit-timing fields.
        // flags: bit12 = FD, bit13 = BRS, bit14 = ESI.
        const QString dlc = QString::number(len2dlc(len), 16);
        const quint32 flags =
            (1u << 12) | (brs ? (1u << 13) : 0u) | (esi ? (1u << 14) : 0u);
        const QString flagsHex =
            QStringLiteral("%1").arg(flags, 8, 16, QLatin1Char(' ')).toUpper();
        const QString body =
            QStringLiteral("CANFD %1 %2 %3  %4 %5 %6 %7 %8 %9 %10 %11 %12 %13 %14 %15 %16 %17")
                .arg(int(f.bus_idx), 3)
                .arg(dir, -4)
                .arg(idStr, 8)
                .arg(QString(), 32) // symbolic name (none)
                .arg(brs ? 1 : 0)
                .arg(esi ? 1 : 0)
                .arg(dlc)
                .arg(len, 2)
                .arg(dataStr)
                .arg(0, 8)          // message duration
                .arg(0, 4)          // message length
                .arg(flagsHex)
                .arg(0, 8)          // CRC
                .arg(0, 8).arg(0, 8).arg(0, 8).arg(0, 8); // bit timing (arb/data/ext)
        return QStringLiteral("%1 ").arg(ts, 13, 'f', 6) + body;
    }

    // Classic line — columns reproduce the reference caninspector.asc alignment:
    // %13.6f timestamp, %4d bus, %10s id, %6s dir, " d", %7d length, space, data.
    return QStringLiteral("%1%2%3%4 d%5 %6")
        .arg(ts, 13, 'f', 6)
        .arg(int(f.bus_idx), 4)
        .arg(idStr, 10)
        .arg(dir, 6)
        .arg(len, 7)
        .arg(dataStr);
}

} // namespace ct
