#include "can_log_export.h"

#include <QFileInfo>
#include <QLocale>
#include <QStringList>

namespace ct {

namespace {

// CAN FD DLC code for a byte count (0-8 map 1:1; 12->9, 16->10, ... 64->15).
// The same table asc_log.cpp keeps to itself; small enough to repeat rather
// than to export.
int len2dlc(int len)
{
    if (len <= 8)
        return len;
    static const int kFd[] = {12, 16, 20, 24, 32, 48, 64};
    for (int i = 0; i < 7; ++i)
        if (len <= kFd[i])
            return 9 + i;
    return 15;
}

QString hexId(const MonitorStreamPayload &f)
{
    const bool ext = f.flags & MONFLAG_EXTENDED;
    return QStringLiteral("%1").arg(f.can_id, ext ? 8 : 3, 16, QLatin1Char('0')).toUpper();
}

QString hexByte(quint8 b)
{
    return QStringLiteral("%1").arg(b, 2, 16, QLatin1Char('0')).toUpper();
}

// Milliseconds since the first buffered frame, clamped at zero: a device
// reboot mid-capture restarts its uptime, and an unsigned subtraction would
// otherwise turn that into a 49-day timestamp.
quint32 relativeMs(const MonitorStreamPayload &f, quint32 t0)
{
    return f.timestamp_ms >= t0 ? f.timestamp_ms - t0 : 0u;
}

bool isFd(const MonitorStreamPayload &f)
{
    return (f.flags & MONFLAG_FD) || (f.flags & MONFLAG_BRS); // BRS is only set on FD frames
}

} // namespace

QString CanLogFormatInfo::filter() const
{
    return QStringLiteral("%1 (*.%2)").arg(name, suffix);
}

const QList<CanLogFormatInfo> &canLogFormats()
{
    static const QList<CanLogFormatInfo> formats = {
        {CanLogFormat::VectorAsc, QStringLiteral("Vector ASCII log"), QStringLiteral("asc")},
        {CanLogFormat::SocketCanLog, QStringLiteral("SocketCAN candump log"),
         QStringLiteral("log")},
        {CanLogFormat::PeakTrc, QStringLiteral("PEAK trace 3.0"), QStringLiteral("trc")},
    };
    return formats;
}

const CanLogFormatInfo &canLogFormatInfo(CanLogFormat format)
{
    for (const CanLogFormatInfo &info : canLogFormats())
        if (info.format == format)
            return info;
    return canLogFormats().first();
}

QString canLogFilterString()
{
    QStringList filters;
    for (const CanLogFormatInfo &info : canLogFormats())
        filters << info.filter();
    return filters.join(QStringLiteral(";;"));
}

QString canLogSuggestedName(CanLogFormat format, const QDateTime &when)
{
    const QLocale c = QLocale::c(); // digits only, but stable regardless of region
    return QStringLiteral("Logged Msgs %1 - %2.%3")
        .arg(c.toString(when, QStringLiteral("yyMMdd")), c.toString(when, QStringLiteral("HHmm")),
             canLogFormatInfo(format).suffix);
}

CanLogFormat canLogFormatFor(const QString &selectedFilter, const QString &path)
{
    const QString suffix = QFileInfo(path).suffix().toLower();
    if (!suffix.isEmpty())
        for (const CanLogFormatInfo &info : canLogFormats())
            if (info.suffix == suffix)
                return info.format;
    for (const CanLogFormatInfo &info : canLogFormats())
        if (info.filter() == selectedFilter)
            return info.format;
    return CanLogFormat::VectorAsc;
}

QString socketCanLogLine(const MonitorStreamPayload &f, quint32 t0)
{
    const quint32 ms = relativeMs(f, t0);
    QString line = QStringLiteral("(%1.%2) can%3 %4#")
                       .arg(ms / 1000u, 10, 10, QLatin1Char('0'))
                       .arg((ms % 1000u) * 1000u, 6, 10, QLatin1Char('0'))
                       .arg(int(f.bus_idx))
                       .arg(hexId(f));
    if (isFd(f)) {
        const int flags = ((f.flags & MONFLAG_BRS) ? 1 : 0) | ((f.flags & MONFLAG_ESI) ? 2 : 0);
        line += QLatin1Char('#') + QString::number(flags, 16).toUpper();
    }
    const int len = qMin<int>(f.data_len, 64);
    for (int i = 0; i < len; ++i)
        line += hexByte(f.data[i]);
    return line;
}

QString trcHeader(const QDateTime &when)
{
    const QLocale c = QLocale::c(); // stable digits and separators
    // Days since 1899-12-30 (the Delphi / Excel serial date), time of day as
    // the fraction. Ten decimals resolve well under a millisecond.
    const double serial = double(QDate(1899, 12, 30).daysTo(when.date()))
                          + double(when.time().msecsSinceStartOfDay()) / 86400000.0;
    QString h;
    h += QStringLiteral(";$FILEVERSION=3.0\n");
    h += QStringLiteral(";$STARTTIME=") + QString::number(serial, 'f', 10) + QLatin1Char('\n');
    h += QStringLiteral(";$COLUMNS=N,O,T,B,I,d,R,L,D\n");
    h += QStringLiteral(";\n");
    // PEAK writes milliseconds then microseconds; the host clock has no
    // microseconds, so they read 000.
    h += QStringLiteral(";   Start time: ")
         + c.toString(when, QStringLiteral("dd.MM.yyyy HH:mm:ss.zzz")) + QStringLiteral(".000\n");
    h += QStringLiteral(";   Generated by CAN Triple Device Manager\n");
    h += QStringLiteral(";-------------------------------------------------------------------------------\n");
    h += QStringLiteral(";   Bus  Connection        Protocol\n");
    for (int bus = 1; bus <= 3; ++bus)
        h += QStringLiteral(";   %1    CAN Triple CAN %1  CAN\n").arg(bus);
    h += QStringLiteral(";-------------------------------------------------------------------------------\n");
    h += QStringLiteral(";   Index      Time    Type    CAN-ID/    Res  DLC Data\n");
    h += QStringLiteral(";   |          Offset  |  Bus  PID    Rx/  |    |\n");
    h += QStringLiteral(";   |          [ms]    |  |    |      Tx   |    |\n");
    h += QStringLiteral(";---+--- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- -- --\n");
    return h;
}

QString trcFrameLine(const MonitorStreamPayload &f, quint32 t0, quint64 index)
{
    const bool fd = isFd(f);
    const bool brs = f.flags & MONFLAG_BRS;
    const bool esi = f.flags & MONFLAG_ESI;
    const QString type = !fd          ? QStringLiteral("DT")
                         : brs && esi ? QStringLiteral("BI")
                         : brs        ? QStringLiteral("FB")
                         : esi        ? QStringLiteral("FE")
                                      : QStringLiteral("FD");
    const int len = qMin<int>(f.data_len, 64);
    const int dlc = fd ? len2dlc(len) : qMin(len, 8);
    QString data;
    data.reserve(len * 3);
    for (int i = 0; i < len; ++i) {
        if (i)
            data += QLatin1Char(' ');
        data += hexByte(f.data[i]);
    }
    // Index right in 8, offset right in 14 with three decimals, id right in
    // 10, DLC left in 4 — the widths PEAK's own example uses. Blank-separated
    // is all a reader needs; the widths keep the file readable as a table.
    QString line = QStringLiteral("%1 %2 %3 %4 %5 %6 - %7")
                       .arg(index, 8)
                       .arg(double(relativeMs(f, t0)), 14, 'f', 3)
                       .arg(type)
                       .arg(int(f.bus_idx))
                       .arg(hexId(f), 10)
                       .arg(f.direction ? QStringLiteral("Tx") : QStringLiteral("Rx"))
                       .arg(dlc, -4);
    if (!data.isEmpty())
        line += QLatin1Char(' ') + data;
    else
        while (line.endsWith(QLatin1Char(' ')))
            line.chop(1);
    return line;
}

QString canLogLineEnding(CanLogFormat format)
{
    return format == CanLogFormat::SocketCanLog ? QStringLiteral("\n") : QStringLiteral("\r\n");
}

QString canLogHeader(CanLogFormat format, const QDateTime &when)
{
    switch (format) {
    case CanLogFormat::VectorAsc:
        return ascHeader(when);
    case CanLogFormat::PeakTrc:
        return trcHeader(when);
    case CanLogFormat::SocketCanLog:
        break;
    }
    return QString();
}

QString canLogFrameLine(CanLogFormat format, const MonitorStreamPayload &frame, quint32 t0,
                        quint64 index)
{
    switch (format) {
    case CanLogFormat::SocketCanLog:
        return socketCanLogLine(frame, t0);
    case CanLogFormat::PeakTrc:
        return trcFrameLine(frame, t0, index);
    case CanLogFormat::VectorAsc:
        break;
    }
    return ascFrameLine(frame, t0);
}

} // namespace ct
