// "Import DBC" — a checkable tree of a parsed .dbc file's messages and their
// signals. The user picks which messages/signals to import, edits the import
// name and Channel Type inline, and chooses the target bus. Multiplexed
// messages import as compound sections (per-value sub-messages).
//
// Two directions. As RECEIVE messages (the default) every ticked signal becomes
// a channel row plus a new User Channel, named and typed from the columns. As
// TRANSMIT messages nothing is created: each ticked signal becomes a row that
// SENDS an existing channel, chosen in the Send Channel column — prefilled
// where a catalogue channel already carries the signal's name, picked through
// the ordinary channel picker otherwise — and a ticked signal with no channel
// is skipped with a note, because a transmit row with nothing to send is not a
// row. The file's offset changes sign on the way in (transmitRowFromDbcSignal)
// and its GenMsgCycleTime becomes the section's period.
#pragma once

#include <QDialog>
#include <QHash>
#include <QList>
#include <QPair>

#include "../model/comms_types.h"
#include "../model/configuration.h" // ConfigPatch
#include "../model/dbc_import.h"

class QAbstractItemDelegate;
class QComboBox;
class QDialogButtonBox;
class QLabel;
class QLineEdit;
class QPlainTextEdit;
class QTreeWidget;
class QTreeWidgetItem;

namespace ct {

class ImportDbcDialog : public QDialog
{
    Q_OBJECT
public:
    // livePatch: the calling dialog's unsaved view of the buses, handed to the
    // channel picker so its "generated by" notes count sections edited in this
    // sitting. See SelectChannelDialog.
    ImportDbcDialog(Configuration *config, const DbcFile &dbc, const QString &sourceName,
                    int defaultBusIndex, const QStringList &parseWarnings,
                    QWidget *parent = nullptr, const ConfigPatch &livePatch = {});

    // Valid after accept(): the bus the user chose, and the sections to add.
    int targetBusIndex() const;
    QList<CommsSection> importedSections() const { return m_sections; }
    // Which way the ticked messages import: receive unless the Import As combo
    // says Transmit.
    bool transmitMode() const;

protected:
    void accept() override;

private:
    void buildTree();
    void rebuildKeepingState();
    void applyFilter();
    void onItemChanged(QTreeWidgetItem *item, int column);
    void onItemDoubleClicked(QTreeWidgetItem *item, int column);
    void pickChannelFor(QTreeWidgetItem *item);
    void updateParentCheck(QTreeWidgetItem *parent);
    void setAllChecked(bool checked);
    void updateOkState();
    // The Send Channel a signal row names, or empty: not transmit mode, not a
    // signal row, or the cell still reads the placeholder.
    QString linkedChannel(const QTreeWidgetItem *item) const;

    Configuration *m_config;
    DbcFile m_dbc;
    ConfigPatch m_livePatch;

    QLineEdit *m_filter = nullptr;
    QComboBox *m_busCombo = nullptr;
    QComboBox *m_modeCombo = nullptr;
    QLabel *m_rateLabel = nullptr;
    QComboBox *m_rateCombo = nullptr;
    QTreeWidget *m_tree = nullptr;
    QPlainTextEdit *m_warnings = nullptr;
    QLabel *m_countLabel = nullptr;
    QDialogButtonBox *m_buttons = nullptr;

    // Receive-mode column editors and the read-only stand-in that every column
    // takes in transmit mode; buildTree() points the tree at one or the other.
    QAbstractItemDelegate *m_nameDelegate = nullptr;
    QAbstractItemDelegate *m_quantityDelegate = nullptr;
    QAbstractItemDelegate *m_unitDelegate = nullptr;
    QAbstractItemDelegate *m_readOnlyDelegate = nullptr;

    // Send Channel choices, keyed (message index, signal index), remembered
    // across a mode change: the tree is rebuilt on every switch, and a channel
    // picked before a look at the receive columns must still be there after.
    QHash<QPair<int, int>, QString> m_links;
    // The mode the tree was last built for. Read wherever the tree's CONTENTS
    // are interpreted, because the combo has already moved on by the time its
    // change handler snapshots the old tree.
    bool m_treeIsTransmit = false;

    QList<CommsSection> m_sections;
    bool m_updating = false; // guards manual parent/child check propagation
};

} // namespace ct
